[font]
size = 11.0

[font.normal]
family = "JetBrains Mono"

[window]
decorations = "None"
startup_mode = "Windowed"
opacity = 1.0
decorations_theme_variant = "None"
dynamic_padding = true
dimensions = { columns = 100, lines = 30 }

[window.padding]
x = 3
y = 3

[colors.primary]
background = '#0a0c10'
foreground = '#f0f3f6'

[colors.cursor]
text = '#181818'
cursor = '#d8d8d8'

[colors.normal]
black   = '#181818'
red     = '#ab4642'
green   = '#a1b56c'
yellow  = '#f7ca88'
blue    = '#7cafc2'
magenta = '#ba8baf'
cyan    = '#86c1b9'
white   = '#d8d8d8'

[colors.bright]
black   = '#585858'
red     = '#ab4642'
green   = '#a1b56c'
yellow  = '#f7ca88'
blue    = '#7cafc2'
magenta = '#ba8baf'
cyan    = '#86c1b9'
white   = '#f8f8f8'
